### ISSUE TITLE
Missing ts-node dependency

### ISSUE THREAD

**Issue by arnaudmanaranche** [ericellb/gitfaker#1]
When running the start command: `npm start`, the following output appeared:

```
sh: ts-node: command not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! git-faker@1.0.0 start: `ts-node src/index.ts`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the git-faker@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

After installing `ts-node` globally (`npm install -g ts-node`), the previous command works.

Maybe it will be useful to add a line on the README to warn users to install this dependency.

**Comment by ericellb** [comment]
Oops, that would have been a good idea to include.

Thanks for the heads up.
